### ISSUE TITLE
using backslach before a variable eats the backslach

### ISSUE THREAD

**Issue by hreintke** [Sloeber/arduino-eclipse-plugin#1166]
In ESP32 platform.txt there is this line  : 
`recipe.hooks.prebuild.2.pattern.windows=cmd /c if not exist "{build.path}\partitions.csv" copy "{runtime.platform.path}\tools\partitions\{build.partitions}.csv" "{build.path}\partitions.csv"
`

Which expanded to : 

`cmd /c if not exist "C:\Userdata\ESP8266\Projects\Command_32/Release\partitions.csv" copy "C:/Userdata/ESP32/arduino_esp32\tools\partitionsdefault.csv" "C:\Userdata\ESP8266\Projects\Command_32/Release\partitions.csv"`

There is a missing backslash from : 
`{runtime.platform.path}\tools\partitions\{build.partitions}.csv`
to 
`C:/Userdata/ESP32/arduino_esp32\tools\partitionsdefault.csv`

Environment : Windows 8.1, Sloeber 4.3.2. (also seen in 4.3.1)

**Comment by jantje** [comment]
This is a cdt issue that won't be fixed quickly
https://bugs.eclipse.org/bugs/show_bug.cgi?id=560330
maybe you can use / to workaround

**Comment by hreintke** [comment]
Using `copy "{runtime.platform.path}\tools\partitions\\{build.partitions}.csv"` in platform.txt makes it work.
Pity that we need a local patch to make it work (=remark to eclipse, not to you).

**Comment by jantje** [comment]
This is now fixed in CDT10 !!!
Not yet released but removing this from the known limitations

**Comment by jantje** [comment]
This is now fixed in the latest nightly

**Comment by AungKL** [comment]
> This is now fixed in the latest nightly

I have the same "partitions.csv" target 'pre-build' failed issue? It's work on 1.0.4, but not on 1.0.5, 1.0.6 and 2.0.0.
I want to update the latest nightly, my current version is   

> Sloeber, the Eclipse Arduino IDE (plugin version)	4.3.3.202004230915
and running on Windows 10 64-bit. 

I'm not a developer, could you please show me the way to update?

Thanks

**Comment by jantje** [comment]
All the info is available on the website http://eclipse.baeyens.it
The nightly link http://eclipse.baeyens.it/nightly.php
The upgrade procedure http://eclipse.baeyens.it/how_to.shtml#/n

**Comment by AungKL** [comment]
Thank for reply,
I chose "method 2. upgrade current product" from [http://eclipse.baeyens.it/how_to.shtml#/n](url)
and able to update 4.3.3.202005042010
but the problem of "partitions.csv" target 'pre-build' failed issue with ESP32 v2.0.0 still not disappear.

**Current Version**

![Sloeber_current_version](https://user-images.githubusercontent.com/76830614/119248923-221acd80-bbc7-11eb-8e00-3704f235f7e8.jpg)


**Available Version**

![Sloeber_available_version](https://user-images.githubusercontent.com/76830614/119248334-0d3c3b00-bbc3-11eb-86fe-85e1dcf909b4.jpg)

**Updated Version**

![Sloeber_Updated_version](https://user-images.githubusercontent.com/76830614/119248740-d74c8600-bbc5-11eb-9bae-a7913ed7588c.jpg)


**ESP32 v2.0.0 Setup**

![Sloeber_ESP32_v2 0 0](https://user-images.githubusercontent.com/76830614/119248345-1927fd00-bbc3-11eb-8f6e-0fe2f097a6f0.jpg)


**ESP32 - "partitions.csv" target 'pre-build' failed issue**

![Sloeber_ESP32_v2 0 0_error](https://user-images.githubusercontent.com/76830614/119248347-1b8a5700-bbc3-11eb-878f-7c6f224fb7e2.jpg)



Is it correct way to update nightly build?

**Comment by jantje** [comment]
>but the problem of "partitions.csv" target 'pre-build' failed issue with ESP32 v2.0.0 still not disappear.

That is because .3.3.202005042010 is not the latest nightly but the latest stable
Did you activate the nightly update site
Note this is a difficult upgrade as you will also have to upgrade java and cdt

**Comment by AungKL** [comment]
After activating the nightly update site, and jre to v11, 

![Nightly](https://user-images.githubusercontent.com/76830614/119262562-40f08280-bc0e-11eb-93f8-a72a27716614.jpg)



then I check for the update, there is an error "No remedy found"

![no remedy](https://user-images.githubusercontent.com/76830614/119262591-5665ac80-bc0e-11eb-82b0-41423fff80ed.jpg)


Could you please help me to show the direction to nightly update?

**Comment by jantje** [comment]
From the link I have send before
![afbeelding](https://user-images.githubusercontent.com/1175841/119263565-da547000-bbdf-11eb-843e-19e6acad4dc3.png)

You are hitting the disadvantages
