### ISSUE TITLE
Debug esp32 FreeRtos applications

### ISSUE THREAD

**Issue by freeck** [Sloeber/arduino-eclipse-plugin#819]
I cannot imagine being the first, but I could not find any procedure on the internet for enabling source level debugging with an JTAG-ICE, using Eclipse and the Sloeber-plugin.
I finally succeeded, so if there is any interest I could publish the procedure.

**Comment by jantje** [comment]
yes there is :-)))

**Comment by jantje** [comment]
FYI
We have been working hard to get regression tests in the build.
Now this is done I want to add my hardware repositories to the regression test as some changes in Sloeber make them fail.
So yes I'm still interested but things do not progress as fast as I would like.

**Comment by freeck** [comment]
No problem, in the mean time I am able to further review and improve the documentation on the installation and debugging process.

**Comment by jantje** [comment]
Have you seen these video's on debug on esp32 and zero?
https://youtu.be/WFzVzgEA8Fo
https://youtu.be/DXTo4-0pWKA
I think I will make time for doing the same with esp32 beginning next year.
Would that fit your agenda?
How is the doc going?
If you prefer dutch we can do the discussion on the Arduino forum like we did for esp8266

**Comment by freeck** [comment]
Yes I have seen your video's. Concerning the esp32: Perhaps you have seen this video https://m.youtube.com/watch?v=xJyNLcoG7Q0 ? It is in German, but the video is very instructive.

As I did not receive any reactions (accept from you) on my plans to make a video, the priority has dropped (I am still very curious about how people can develop software especially for embedded systems, without a proper debugger).

OK, I will make a document for "setting up the debugging environment for a esp32-target" before the first of January..

**Comment by freeck** [comment]
...2018

**Comment by jantje** [comment]
I created a thread in the dutch part of the Arduino forum
http://forum.arduino.cc/index.php?topic=516773.0

**Comment by Develectronic** [comment]
dear freeck,
I am very very interested in debugging the esp32 in slober. I looking for a tutorial on the internet for hours, but there is absolutely nothing. And when I got that right, you have found a way to to that. I would be so thankfull, if you could give me the instructions how to configure sloeber to debug the esp32.

Thanks a lot.

**Comment by Develectronic** [comment]
As you also mentioned above, I cannot understand how other people developing software without debugging. 
But I guess most peoble do not know that it is even possible and others have just no idea how to get it working (like me). 
That would be a second christmas if you produced a document by the end of this week.
Thanks a lot!!!!!

**Comment by Develectronic** [comment]
and yes I know there is jtag interface required. I've alread an xds100v2 or an olimex arm-usb-ocr ( https://www.olimex.com/Products/ARM/JTAG/ARM-USB-OCD/ ) when neccessary I buy another...

**Comment by freeck** [comment]
Hi there, Am I saved by the bell even before the weekend? :)
Have you already read this document? 
https://esp-idf.readthedocs.io/en/latest/api-guides/jtag-debugging/
It does not describe the integration with Sloeber but the most difficult part i.e. the installation and testing of the jtag-interface with the esp32 target and usage of openocd with the gdb for the extensa-processor. 
So could you first try this?

**Comment by Develectronic** [comment]
Hi, 
yes I've seen this side already, but I thougt that it works only for IDF project, when it is more or less the same for sloeber I can try it and may ask some specific questions. 
But is there an relation between this FreeRTOS and the JTAG debugguing? I should be able to debug every "arduino-sketch", right?

**Comment by freeck** [comment]
1: JAG/openocd is meant as a standard interface with any IDE or via a command line interface.
So first try to install and test openocd and test it via a command line as described in the document.

2: "debug every arduino-sketch"? it depends whether the processor you use has a jag-interface... the Atmega328 does not have a Jtag-interface. FreeRtos is used on the esp32 standard environment. It had no link with jtag as such.

**Comment by jantje** [comment]
If you install the zero package you have open ocd in sloeber
If the communicatio, is openocd the "sloeber" side is the same as the zero
https://www.youtube.com/edit?o=U&video_id=DXTo4-0pWKA

PS I say "sloeber" as it is actually gnumcu plugin that delivers this debug stuff

**Comment by freeck** [comment]
I was not aware that this video I made was still in the cloud ! 😂
I now feel myself more or less obliged to finish the video....

**Comment by Develectronic** [comment]
Ok, thank you for the tips. The video is no longer accessible (or link does not work), but can I use this one for the zero package installation? https://www.youtube.com/watch?v=WFzVzgEA8Fo 
Then I need to do the esp32- and JTAG hardware specific configuration?

**Comment by jantje** [comment]
the link was wrong this the correct one https://youtu.be/DXTo4-0pWKA

**Comment by freeck** [comment]
Great video!  As it bases on an ARM-processor I will add the esp32 specific items. 
So @Develectronic be patient for a day or two....

**Comment by freeck** [comment]
Hi folks, I produced a document I placed on Onedrive. A concept so any comment is welcome.
Are you able to open it?
https://1drv.ms/w/s!AgjNziQJTfNOhrlUJad5txK8jXhrTA

**Comment by jantje** [comment]
I can open the files but I won't be able to address this in the first coming days.
I did however create a json to install esp32 easily. I only tested on windows so please feedback if it works or doesn't work for you
https://raw.githubusercontent.com/jantje/arduino-esp32/master/package/package_Espressif_esp32_index.json

**Comment by freeck** [comment]
It works OK with Sloeber4.1, I with test it with Sloeber4.2 asap..

**Comment by freeck** [comment]
Jantje,
I have reached another milestone: after a lot of trial and error, programming the flash via the jtag-interface is now working. I have updated the installation tutorial:
https://1drv.ms/w/s!AgjNziQJTfNOhrlUJad5txK8jXhrTA 


Two minor issues remain:
- it would be nice to link the download button to the jtag-flashing procedure 
- in the debug configuration the working directory macro/variable does not work (at least in my environment). I solved this by including the full path of the bin-file. I lack the Eclipse-knowledge to solve this....

**Comment by freeck** [comment]
And a video on YouTube: https://youtu.be/hxOB7Qp0yM0

**Comment by jantje** [comment]
Sorry for the silence. I'm really busy right now and will be until September. But I do hope to get this to work for the fri3d camp in august.

**Comment by jantje** [comment]
Great video :-) I added it to my sloeber channel.
Next is reading the installation tutorial

**Comment by jantje** [comment]
Reading the doc I wonder if there is any need for a change in Sloeber :-D
In the doc I read "Only two hardware breakpoints are supported."
I don't really understand the user impact of this. I guess there are hardware breakpoints and software breakpoints but what are the differences? Do you know by now?

**Comment by freeck** [comment]
See also: http://esp-idf.readthedocs.io/en/latest/api-guides/jtag-debugging/tips-and-quirks.html

In case the user defines more breakpoints you have to add the IRAM-directive in the header of the function(s) you want to debug. In case you dont you will get an error message in de the debug-console of gdb. It has no consequences for Sloeber...

**Comment by jantje** [comment]
That is exactly what I wanted to know :-)
Thanks

**Comment by easyvolts** [comment]
Hi freeck,

thank you for the manual, it's very helpful. I used it some days ago and had a problem with esp32 jtag not detected by the openocd, the problem was in esp32 board. It needs to have JTAG debugging enabled because one of JTAG pins is used by bootloader (this is strange enough because I thought that openocd connects to the device under reset, but it worked for me). JTAG can be enabled in menuconfig. Probably it would be good to add this information to the document.

**Comment by freeck** [comment]
@easyvolts Thanks for your comment. 
The instruction was specifically written for Sloeber/Windows…. I do not know whether menuconfig can be executed within Sloeber or as a stand alone program?
Perhaps someone can tell me, then I have learned something today! :-)

**Comment by freeck** [comment]
Great, You have passed the most "difficult part" of the installation process i.e. getting the jtag-driver work together with gdb. 
The next step is to follow the instructions decribed in https://onedrive.live.com/view.aspx?resid=4EF34D0924CECD08!105684&ithint=file%2cdocx&app=Word&authkey=!ACWnebcSvI14a0w .....

**Comment by RA5040** [comment]
Many thanks Fred (I've just seen your first name on your article ... hope you don't mind the familiarity :)).  Since posting I have installed gdb/jtag on Eclipse (following the Espressif instructions) and successfully built and debugged the blink example. 

But not without some problems of course.  The main problem was that Eclipse (with the Espressif settings) does not start OpenOCD. I get an error saying "Failed to execute MI command:
-target-select remote localhost:3333".  As far as I can see there is nowhere to set up the debugger information required (the command line to start it is bin/openocd -s share/openocd/scripts -f interface/ftdi/esp32_devkitj_v1.cfg -f board/esp32-wrover.cfg. In Eclipse I can't see where to set up the interface and board configs .... but perhaps after reading your article all will be clear!).

I've written up the steps here: http://www.irelandupclose.com/customer/esp32/jtag/JTAG_ECLIPSE.html

I must say that it's quite a buzz seeing the debug environment pop up!  It was great on the command line, but on Eclipse ... double-great!  

Now for Sloeber ... fingers crossed ...

**Comment by freeck** [comment]
Did you compare your setup with the screendumps  I added in my instruction? From what I read in your instruction you havent....

**Comment by RA5040** [comment]
Yes, I'm going to do that ... I just wanted to build up to it from the Espressif instructions (command line, then Eclipse ... and once I had that working to move on to Sloeber).

The thing is .... which is crazy ... I need to install V4.3 of Sloeber and I can't find it anywhere.  The link to the plug-in: http://eclipse.baeyens.it/update/V4/stable is broken.

Can you ... or Jantje ... tell me where to get it?

**Comment by RA5040** [comment]
OK ... I can see that the plugin comes with the latest version of Eclipse. But I can't get it to run so I need some help from jantje.

**Comment by RA5040** [comment]
Hi Fred,
I've tried your instructions and so far no luck.

Here are the settings and the error log.  As you can see it is failing to find "target/esp32.cfg" in the board config (esp32-wrover.cfg).  
![openocddebugsettingsfk](https://user-images.githubusercontent.com/41873698/44631501-cd3dc000-a964-11e8-9c58-cf4cb8a176fd.jpg)

The manual command (which works, is this:)
bin/openocd -s share/openocd/scripts -f interface/ftdi/esp32_devkitj_v1.cfg -f board/esp32-wrover.cfg

so I tried this line in the Config options:
-s C:\msys32\home\Robert\esp\openocd-esp32\share\openocd\scripts -f C:\msys32\home\Robert\esp\openocd-esp32\share\openocd\scripts\interface\ftdi\esp32_devkitj_v1.cfg -f  C:\msys32\home\Robert\esp\openocd-esp32\share\openocd\scripts\board\esp32-wrover.cfg

This time it didn't fail on the esp32.cfg (so I guess it found the file), but it did fail with this error message:

Error in final launch sequence
Failed to execute MI command:
continue
Error message from debugger back end:
Warning:\nCannot insert breakpoint 1.\nCannot access memory at address 0x400d0ad8\nCannot insert breakpoint 3.\nCannot access memory at address 0x400d0ae2\n
Failed to execute MI command:
continue
Error message from debugger back end:
Warning:\nCannot insert breakpoint 1.\nCannot access memory at address 0x400d0ad8\nCannot insert breakpoint 3.\nCannot access memory at address 0x400d0ae2\n
Warning:\nCannot insert breakpoint 1.\nCannot access memory at address 0x400d0ad8\nCannot insert breakpoint 3.\nCannot access memory at address 0x400d0ae2\n

Any ideas?

BTW, I did get the debugger to work well with C++ programs, but it's a different setup and it didn't work with Sloeber.

Cheers

Robert

**Comment by freeck** [comment]
Hi Robert,

Your setup seems to be OK.
It seems as if you defined too many breakpoints; so I would suggest to delete all the breakpoints and restart the debug process and see what happens..

**Comment by freeck** [comment]
Aha...so somewhere the debugger tries to insert a breakpoint also in case there seems to be no breakpoints defined...
Question: At the location of xtensa-elf-gdb.exe: is there a file called gdbcmds? If so the content of this file could interfere with the startup configuration (there could be a breakpoint set at a non-existing location.... If so, delete this file....

**Comment by RA5040** [comment]
No, unfortunately there's no gdbcmds file, just the xtensa exes and one config file: xtensa-esp32-elf-ct-ng.config (or anywhere else in the msys32 folders).

I tried to debug in RAM but I get the same error, just at a different address. 

So even with no breakpoints at all and no halt at loop, there is still this error:

Warning:\nCannot insert breakpoint 1.\nCannot access memory at address 0x400e8c28\n

Regarding the breakpoint: is there a breakpoint automatically set at main?  That would explain the breakpoint issue.

Which leaves 'Cannot access memory at address xxxx'.  I had thought that this was in reserved memory, but it isn't. So why the error?

When you say you could reproduce the error with gdbcommands, did you also get the memory error?

**Comment by freeck** [comment]
I have a problem... I am not able to reproduce the error message anymore. It now only occurs when I define more than 2 breakpoints. Then I get the same error message as you except at another address.

> Error in final launch sequence
Failed to execute MI command:
continue
Error message from debugger back end:
Warning:\nCannot insert breakpoint 3.\nCannot access memory at address 0x40080e24\n
Failed to execute MI command:
continue
Error message from debugger back end:
Warning:\nCannot insert breakpoint 3.\nCannot access memory at address 0x40080e24\n
Warning:\nCannot insert breakpoint 3.\nCannot access memory at address 0x40080e24\n

A few things I can imagine:
1: I have copied "xtensa-esp32-elf-gdb.exe" to a separate directory (no interference with some configuration file)
2: Which version of "xtensa-esp32-elf-gdb.exe" do you use? (I have tried 2 versions: September 2017 and June 2018, both work).

**Comment by RA5040** [comment]
The toolchain is the 20180110 version and the openocd is 20180724 ... or at least these are the files that I downloaded (pretty sure I installed them). But I'll get the latest stable releases and have another go. And I will also try moving the xtensa...gdb to a different foler.

At least it's (hopefully) a good thing that you are getting a similar error: but why my system is trying to insert breakpoint 1 is certainly a puzzle!  I don't suppose Jantje would have any ideas?

Another thing I'll do is to try it on a different sketch and also on Sloeber 4.3 (I running 4.2 at the moment). Which version are you using?

**Comment by freeck** [comment]
I am running on Sloeber 4.1 . Tomorrow I will try both 4.2 and 4.3.
According to this link https://github.com/espressif/openocd-esp32/issues/51 
Openocd.exe relates to the error I observed , but for me it did not work.

**Comment by RA5040** [comment]
Do you mean the <2 breakpoints? I also saw that somewhere else (but as a programmed restriction). Not sure where that was though. But if you can do more than 3 bpts then that's great.
I'm going to do the following:
i. Try on a C++ program in case it's a Sloeber issue (I couldn't run GDB Hardware Debugging on Sloeber either, but it works on C++).
ii. Move the xtensa-gdb.exe somewhere else
iii. Make absolutely sure the toolchain and OpenOCD are up to date (pretty sure they are)
iv. Try on Sloeber 4.3
v. Try GDB Hardware Debugging again to see if it's the same issue (I can't remember what the error was)

If you have any other suggestions let me know. BTW ... thank you very much for the help!! I would be lost on my own.

**Comment by freeck** [comment]
No, I was able to set 2 breakpoints. One should be able to set more software breakpoints using the IRAM directive, but it does not work for me.

**Comment by RA5040** [comment]
OK ... well for now I would be happy to be able to set 1 breakpoint!

**Comment by RA5040** [comment]
https://github.com/espressif/openocd-esp32/issues/51 ... seems the 2-bpt issue is fixed

**Comment by freeck** [comment]
Yes but it did not work with my configuration. I wil double check my configuration and test it once again. Are you sure that things works OK for you in case using command lines? Could you log the gdb-output and compare it with the log using Sloeber?

**Comment by RA5040** [comment]
I've run a c-program test with 4 breakpoints using OpenOCD, no problem.  I ran the same program with Hardware debug with 6 breakpoints, also fine.

BTW ... one issue I had was that in my first test I was just assigning some values to a couple of variables and the debugger went mad after first Next with lots of:
Info : Target halted. PRO_CPU: PC=0x400D1F49 (active)    APP_CPU: PC=0x400D17AE 
Info : Target halted. PRO_CPU: PC=0x400D1F49 (active)    APP_CPU: PC=0x400D17AE 
...

I saw that the compiler was optimising out the code because the variables were not used, so I set them to volatile and then everything worked OK.  So that's something to watch out for (the debugger doesn't really like empty programs!).

**Comment by RA5040** [comment]
Going back to OpenOCD on Arduino:
**i. Try on a C++ program in case it's a Sloeber issue (I couldn't run GDB Hardware Debugging on Sloeber either, but it works on C++).** WORKS OK
**ii. Move the xtensa-gdb.exe somewhere else**  NO DIFFERENCE
iii. Make absolutely sure the toolchain and OpenOCD are up to date (pretty sure they are): NOT DONE YET
iv. Try on Sloeber 4.3: NOT DONE YET
**v. Try GDB Hardware Debugging again to see if it's the same issue (I can't remember what the error was)**  DOESN'T WORK ... SIMILAR ISSUE (see below):
Error: esp32: Faied to read insn (-4)!
Error: esp32: Faied to add SW BP!
Error: can't add breakpoint: resource not available

So, to summarize so far: [Hardware: ESP32 Wrover Kit; Windows 10; Propably latest versions of tooltchain, OpenOCD, ESP-IDF (to be confirmed)]:
-  Both OpenOCD and Hardware debug work on C programs on Eclipse (that's something!!); 
- Neither OpenOCD nor Hardware debug work on Arduino programs on Eclipse Sloeber V4.2.

TO BE CONTINUED :)

**Comment by freeck** [comment]
I have tried 4.3. I observe that the gdb-client has minor GIU changes. Good news is that the debuggers works fine. Bad news: I still cannot insert more than 2 breakpoints.
error log:
Warn : xtensa_add_breakpoint: max HW slot reached, slot=2
Error: No flash at address 0x400d08d0
Error: Failed to get flash bank (-4)!
Error: esp32: Failed to add SW flash BP!
Error: can't add breakpoint: resource not available

**Comment by RA5040** [comment]
Good and bad for you ... but not good for me: I get the same error.  So at least this has nothing to do with the version of Sloeber. But it would seem to have something to do with Sloeber/ESP32 Dev Module.

In fact, I'm thinking that perhaps that is the problem, because I get the identical error if I change to the ESP Wrover module (which doesn't have JTAG).  What do you think?  Could that be it?

**Comment by freeck** [comment]
I dont understand what you mean by "perhaps that is the problem, because I get the identical error if I change to the ESP Wrover module (which doesn't have JTAG)."  As you dont have a jtag, what error are you refering to?
 I will first test the command line interface trying to define more breakpoints in order Sloeber is excluded.

**Comment by freeck** [comment]
Well I have tested gdb and openocd without Sloeber, and get the same error messages. I cannot insert more than 2 breakpoints. 
So we may for now exclude Sloeber as the source of the problem....

**Comment by RA5040** [comment]
We're talking about two problems at once:
- multiple breakpoints: I don't have a problem with this because I can set multiple breakpoints both with OpenOCD and Hardware gdb.  However you do have a problem because you can only set 2 breakpoints.  I didn't suggest that this was an issue with Sloeber, although as I can't run gdb with Sloeber I can't verify it (but you seem to be excluded Sloeber, so that's good).
- the second problem, which is the one I have, is that I cannot run gdb (either OpenOCD or Hardware gdb) with Sloeber: I get the "Cannot set breakpoint error" and the debug crashes out. But I can run both OpenOCD and Hardware debug with C and C++ apps.  The ESP Wrover Kit does have built-in JTAG and should work with Sloeber and OpenOCD (or Hardware debug), but it doesn't. Trying to debug on it behaves exactly as it does if I select the ESP Wrover module (which does not have JTAG built-in).  So what I was wondering is this: is it possible that Sloeber is incorrectly selecting the ESP Wrover Kit, so that I am effectively trying to run gdb on a board that does not support it?

**Comment by jantje** [comment]
>the second problem, which is the one I have, is that I cannot run gdb (either OpenOCD or Hardware gdb) with Sloeber

have you run gdb from the command line? maybe you are missing a library.

**Comment by freeck** [comment]
I have found the solution, at least for my problem, but this could be a hint for you as well.
I have downloaded the latest version of esp32.cfg , from the sources of OpenOcd! Not the latest zip-file. 
This file seems to "control" the behaviour of gdb and openocd. Now I am able to set multiple breakpoints. Hope this might help you as well.

Answering to your question: Did you you install 2 platforms? If so delete one and test once again.
But I would bett on the configuration file of the target!

**Comment by freeck** [comment]
I have found the solution, at least for my problem, but this could be a hint for you as well.
I have downloaded the latest version of esp32.cfg , from the sources of OpenOcd! Not the latest zip-file. 
This file seems to "control" the behaviour of gdb and openocd. Now I am able to set multiple breakpoints. Hope this might help you as well.

Answering to your question: Did you you install 2 platforms? If so delete one and test once again.
But I would bett on the configuration file of the target!

**Comment by RA5040** [comment]
Jantje ... no I haven't tried to run gdb from the command line on Sloeber code (but I have on C/C++ code). I'll try that.
Fred ... that sound very promising (and I'm delighted to hear you've fixed your problem! ...GREAT!!).  I will need to use the ESP Wrover because it says that:
#   For ESP32-WROVER module use 'esp32-wrover.cfg' configuration file
#   ESP-WROOM-32 and ESP32-WROVER have different flash voltage setting
So I'll download this one and try it:
https://github.com/espressif/openocd-esp32/blob/master/tcl/board/esp32-wrover.cfg
Mind you ... this is one year old so it's probably the same one I'm using. Fingers crossed!

**Comment by RA5040** [comment]
Is this the esp32.cfg you used?
https://github.com/espressif/openocd-esp32/blob/master/tcl/target/esp32.cfg

**Comment by freeck** [comment]
Oh....I thought you had tested command line debugging already....that will reveal the problem! (I think l:)). 

Concerning 1 year old cfg file: No problem, it includes the latest version of esp32.cfg

**Comment by RA5040** [comment]
I downloaded the esp32.cfg from the link above and it is identical to the one I already have.  When you say you downloaded it from the the sources of OpenOCD, could you give me the link please? I can't find it.

I've run the sketch from the command line and it's certainly a lot better. The program halts at loop and I can do a Next. However it crashes on the second Next:

Temporary breakpoint 1, loop () at ..\Blink.ino:24
24      void loop() {
(gdb) l
19        // initialize digital pin 13 as an output.
20        pinMode(2, OUTPUT);
21      }
22
23      // the loop function runs over and over again forever
24      void loop() {
25        digitalWrite(2, HIGH);   // turn the LED on (HIGH is the voltage level)
26        delay(1000);              // wait for a second
27        digitalWrite(2, LOW);    // turn the LED off by making the voltage LOW
28        delay(1000);              // wait for a second
(gdb) n
25        digitalWrite(2, HIGH);   // turn the LED on (HIGH is the voltage level)
(gdb) n
Warning:
Cannot insert breakpoint 0.
Cannot access memory at address 0x400d0ae2

__digitalWrite (pin=0 '\000', val=0 '\000')
    at C:\Users\Robert\git\arduino-esp32\cores\esp32\esp32-hal-gpio.c:173
173     {
(gdb)

It appears to be unable to insert a breakpoint.  Does this mean something to you?  BTW, I set no breakpoints in the sketch.

**Comment by RA5040** [comment]
Sorry, I meant to say that I did try setting a breakpoint and doing a continue. Here is an example:

Temporary breakpoint 1, loop () at ..\Blink.ino:25
25      void loop() {
(gdb) l
20        pinMode(2, OUTPUT);
21      }
22
23      // the loop function runs over and over again forever
24      int i = 1000;
25      void loop() {
26      //  digitalWrite(2, HIGH);   // turn the LED on (HIGH is the voltage level)
27        delay(i);              // wait for a second
28      //  digitalWrite(2, LOW);    // turn the LED off by making the voltage LOW
29        delay(i/2);              // wait for a second
(gdb) break 27
Breakpoint 2 at 0x400d0adf: file ..\Blink.ino, line 27.
(gdb) c
Continuing.
Warning:
Cannot insert breakpoint 2.
Cannot access memory at address 0x400d0adf

Weird ... it says that it did insert a breakpoint at 0x400d0adf, and then it says that it can't access that location!

**Comment by RA5040** [comment]
But yes, there is progress.

- the program stops at 'loop' as requested
- I can 'continue' and it will run fine
- I can set a breakpoint
x The program stops at the breakpoint but not correctly ... but if I delete the breakpoint I can then 'continue'
x Next works a bit (once)

I'll try modifying the esp32wrover.cfg to run only on one cpu to simplify things a bit.

BTW ...  a similar C program (but one which uses freeRTOS and a task) runs perfectly both from the command line and Eclipse (just a reminder :))

**Comment by freeck** [comment]
Perhaps the optimiser causes this, you have 2 statements with delay(i) and delay(i/2)....the optimiser could make delay(1,5) l:). Perhaps you could try br at 25 or any other statement.

**Comment by freeck** [comment]
"freeRTOS and a task) runs perfectly both from the command line and Eclipse ... with lots of breakpoints (just a reminder :))". 
Yes I am at the same stage I inserted 4 breakpoints and the debugger stops everwhere with Sloeber l:) .

**Comment by freeck** [comment]
"freeRTOS and a task) runs perfectly both from the command line and Eclipse ... with lots of breakpoints (just a reminder :))". 
Yes I am at the same stage I inserted 4 breakpoints and the debugger stops everwhere with Sloeber l:) .

**Comment by freeck** [comment]
I think the next-statement doesnt work as you exit the loop()function. as the function loop() is the entry-point of the debugger the caller is unknown

**Comment by freeck** [comment]
I was too prematurely: I had added directive IRAM_ATTR to my sources. Try that and perhaps now you are successful. If you don't I get the same error as you!? 
Error: can't add breakpoint: resource not available
Info : Target halted. PRO_CPU: PC=0x400D3DCE             APP_CPU: PC=0x40080D7A (active)
Error: esp32: Faied to read insn (-4)!
Error: esp32: Faied to add SW BP!
Error: can't add breakpoint: resource not available

You can avoid this by defining a hardware breakpoint of the breakpoint properties.

**Comment by RA5040** [comment]
I was just about to give you an example that showed that it worked with hardware breakpoints (but I don't know why the debugger decided in one case to use hardware breakpoints and not the second time).  What the debugger said (when it worked) is:
"Note: automatically using hardware breakpoints for read-only addresses."

I'm not sure if I understand you, but I take it you are NOT suggesting that I ADD IRAM_ATTR?

How do I define hardware breakpoint in the breakpoint properties?

I suppose an alternative would be to run the program in RAM?

**Comment by freeck** [comment]
A program in RAM only works with very small programmes...
Breakpoints properties can be set in Sloeber... In a debug session the breakpoints TAB shows the Breakpoints defined. Right-click and you see the properties.

**Comment by RA5040** [comment]
Could you tell me how to set the hardware breakpoint attribute in Sloeber please? I would like to try that as so far nothing else has worked (I tried using IRAM_ATTR, but that's the same).

From the command line, using hbreak instead of break does work, but the whole thing is unreliable. For instance, I can set two hbreaks (max of 2), and continue happily from one to the next. Then I press N and the debug fails ... it seems to go into the function and is unable to set a breakpoint at that address.

**Comment by freeck** [comment]
See my video: 
"And a video on YouTube: https://youtu.be/hxOB7Qp0yM0

**Comment by RA5040** [comment]
You won't believe this, but I am actually debugging using Sloeber at the moment!  I'm in a complete state of shock!!

There's definitely an initialization issue somewhere. What I did was to ignore the error when I started the debugging. Then I opened the Breakpoints tab, which had a bunch of breakpoints (I was not seriously thinking that this would fix anything so I didn't take much note except that all of the breakpoints were in main (I'm pretty sure)). 

Then I tried debugging again, except that this time no errors, but no break in the program either, so I couldn't step or anything.

I then put in a breakpoint and restarted the debug using the icon with the small arrow with the return arrow underneath it (restart a process or debug without terminating etc). The program then halted at my breakpoint and I was then able to debug!  God must have taken pity on me :)

Anyway, I don't think this is a solution, but it might point to one .... for tomorrow I think!

**Comment by RA5040** [comment]
And I can put in 4 breakpoints (my program only has 4 lines so I can't try any more :))

**Comment by RA5040** [comment]
And it seems there's something else: this only works with IRAM_ATTR set. The problem with that is that it forces the code into RAM ... so it will limit the size of the program, and it also no longer correctly matches the program that will be in ROM.

This is not something that is needed with C/C++ programs ... but if there's no alternative then at least it's a way to debug using Sloeber (but I think this needs to be looked into properly ... I mean not by me, but by Jantje and maybe you ... with help from GitHub or whatever). It shouldn't be necessary to use the IRAM_ATTR.

**Comment by freeck** [comment]
Concrats so far! 
Mind you: the esp32 debugger isnt perfect, it has all to do with the limited hardware-breakpoints, see all the issues around this subject described in readthedocs. It is not an issue of improving Sloeber. I think there is still  an ongoing process of improving OpenOcd.

**Comment by freeck** [comment]
Concrats so far! 
Mind you: the esp32 debugger isnt perfect, it has all to do with the limited hardware-breakpoints, see all the issues around this subject described in readthedocs. It is not an issue of improving Sloeber. I think there is still  an ongoing process of improving OpenOcd.

**Comment by freeck** [comment]
I cannot open this video! Could you check the link?

**Comment by RA5040** [comment]
[http://www.irelandupclose.com/customer/esp32/jtag/commandlinedebug.avi](url)

**Comment by RA5040** [comment]
Sorry, I put in the wrong link ... correct one above

**Comment by freeck** [comment]
Still doesnt work...It enters a GitHub-page: https://github.com/Sloeber/arduino-eclipse-plugin/issues/url

**Comment by RA5040** [comment]
Seems like currently GDB can't set software breakpoints in flash so they are emulated by hardware breakpoints or 'software flash breakpoints', whatever they are. So it doesn't make any difference if I use hbreak or break as I'm debugging in flash.

**Comment by RA5040** [comment]
You will have to copy and paste the link in your browser ... I don't know why it's redirecting you to github (presumably to stop people hijaking the site ...)

**Comment by freeck** [comment]
> Seems like currently GDB can't set software breakpoints in flash so they are emulated by hardware breakpoints or 'software flash breakpoints', whatever they are. So it doesn't make any difference if I use hbreak or break as I'm debugging in flash.

As I stated a number of times in this "chat".... But you claimed you saw in the video that setting more than 2 breakpoint in flash was possible. So what version of openocd did he use?

**Comment by RA5040** [comment]
I recorded this video.  As I said, I can set multiple breakpoints if I debug C/C++ programs, either in command line or from Eclipse.  I'm using the latest software ... OpenOCD version openocd-esp32-win32-0.10.0-esp32-20180724

**Comment by freeck** [comment]
OK, even better that it was your video, I am very curious to see it. The more as the authors of readthedocs state that is not possible .....Is there another way to exchange the video, do you have onedrive?

You use the same version of OpenOcd  as I use.

**Comment by freeck** [comment]
> As I said, I can set multiple breakpoints if I debug C/C++ programs,
To be sure: on a esp32 target?

**Comment by RA5040** [comment]
Yes, I am debugging on an ESP32 target (the ESP32 WROVER DEV KIT with JTAG).
Sure, I can put the video up on youtube. Here it is: https://www.youtube.com/watch?v=D-SxjrGcHtU&feature=youtu.be

**Comment by RA5040** [comment]
Actually, I see that if I use the link (above) to link to a video it branches to github.  If I don't use the link, as here
http://www.irelandupclose.com/customer/esp32/jtag/commandlinedebug.avi
you should be able to download the video (which will be better quality than youtube).

**Comment by freeck** [comment]
Yes now I can see the video. Great to see the debugging works this way! 
I observe that you use the same versions of gdb and openocd. So I am going to try it myself.

**Comment by freeck** [comment]
Great puzzle!  I get this message after defining more than 2 breakpoints....
"You may have requested too many hardware breakpoints/watchpoints"
Just to be sure:
Open On-Chip Debugger 0.10.0-dev (2018-07-24-09:39)
GNU gdb (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 7.10
esp32.cfg: 16-1-2018

**Comment by freeck** [comment]
One difference I notice: I see that you use hardware debugging. Did you try openocd also?

**Comment by RA5040** [comment]
In the video I'm using OpenOCD.  This is the command line I use (exactly the same as in my settings on Sloeber):
bin/openocd -s share/openocd/scripts -f interface/ftdi/esp32_devkitj_v1.cfg -f board/esp32-wrover.cfg

Have you tried debugging a C program rather than an Arduino program?  You could try the one below.  The other difference is that I am using a Wrover Kit whereas you are using an external JTAG.


#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/gpio.h"
#include "sdkconfig.h"


#define BLINK_GPIO 2

void blink_task(void *pvParameter)
{

    gpio_pad_select_gpio(BLINK_GPIO);

    gpio_set_direction(BLINK_GPIO, GPIO_MODE_OUTPUT);
    while(1) {

        gpio_set_level(BLINK_GPIO, 0);
        vTaskDelay(1000 / portTICK_PERIOD_MS);
        gpio_set_level(BLINK_GPIO, 1);
        vTaskDelay(1000 / portTICK_PERIOD_MS);
    }
}

void app_main()
{
    xTaskCreate(&blink_task, "blink_task", configMINIMAL_STACK_SIZE, NULL, 5, NULL);

}

**Comment by freeck** [comment]
OK I will try it asap.

**Comment by freeck** [comment]
According to your project settings the program runs in RAM.... is that correct? That would explain why more than 2 breakpoints are accepted?
In case you uncheck "Debug in RAM" , what happens?uld it be that you have built and debugged in RAM?

**Comment by RA5040** [comment]
Where do you see 'Debug in RAM'?

**Comment by freeck** [comment]
When I defined the debug session: in the startup-tab that parameter was checked. Perhaps that was a setting of an earlier defined debug session. So you didnt check this parameter?

I could not build your project in Sloeber , so I used the bin-file to program the target and the elf-file to debug. The session started and stopped at a breakpoint, but not a the exact line of blink.c , so the build was not up to date I guess.

**Comment by RA5040** [comment]
I built the file from the command line. So if you unzip the folders at:
C:\msys32\home\Robert\esp (or wherever you have your esp-idf), then in the blink file you need to do:
make menuconfig            ... to set your port number
make flash                        ... to make and flash the project
./runblink.sh                     ... just a script to kick of gdb

But before you run gdb, you need to start openocd.  There is a bug that requires this ... it's being looked at currently (if you run openocd before the flash it won't/may not work).

If you like I can zip up my whole msys32  folder and send it to you ... at least that way we would be using exactly the same software.

**Comment by freeck** [comment]
That is quit a hassle as I am not familiar with IDF and have not installed it.

However I still get the same error with your example:
Info : Target halted. PRO_CPU: PC=0x400D1FD8 (active)    APP_CPU: PC=0x400D1816 
Info : Target halted. PRO_CPU: PC=0x400D1FAB (active)    APP_CPU: PC=0x40080340 
Error: esp32: Faied to read insn (-4)!
Error: esp32: Faied to add SW BP!
Error: can't add breakpoint: resource not available

I suppose we should have a break...and wait for inspiration |:)  I have spent a lot of my time on this subject. Aren't there any other collogues who can support us on the IDF-fora?

**Comment by RA5040** [comment]
Yes, it may be a good idea to take a break. I'm trying to keep up on my project and get this working at the same time and it's a bit of a struggle ... and probably not the best way to keep a clear head.

I have already zipped up the msys32 and I do think it would be worth trying ... although it could be another rabbit hole! Anyway I'll stick it up in the cloud somewhere so you can access it if you decide to give it a go.

At this point I can debug in Sloeber up to a point, as long as the IRAM_ATTR is set, which isn't great at all, IMO.  

The alternative is to go back to C/C++ as that does work (although I do like Sloeber and would prefer to stay with it),. There is a way of doing this which is pretty painless (if it works) as you can use Arduino code with your C/C++:
https://github.com/espressif/arduino-esp32/blob/master/docs/esp-idf_component.md
I had a quick go but got a compilation error and haven't looked further into it.

Probably time for a real Sloeber and a break :)

**Comment by freeck** [comment]
Yeah! I will wait for your link to the zip-file.

Btw: is there any link to the activities you are involved in? As a professional or pensionado :) or both?

**Comment by RA5040** [comment]
At the moment I'm a pensionado who is busier than when I was working!  I'm an engineer by profession with a background in automation and telecommunications, but now I paint (a lot!) and photograph and do some projects like the one I'm working on now, which is instrumenting a coffee roaster. 

It's quite an interesting project which involves both manual and computer control of the roaster, with graphs on the computer (the computer software is written in Java).  The project has 3 microcontrollers: the first is the main one which controls the motor, fan and heater and has two thermocouple inputs and a drum sensor position input.  It interfaces to the other modules and to the computer. The second is the manual control module which allows the operator to control the whole thing manually.  The third is a temperature monitoring module which sits on the roasting drum (and rotates with it :)) and sends the temperature data to the main controller using ESP-NOW.  I have all it working in sections and now I need to integrate it all. Then I will need to design and build the pcbs.  

I've also developed some digital painting tools which give me quite a nice revenue: http:www.paintingdigitally.com

So that's about it, apart from the rest of life :)

What about you?

**Comment by freeck** [comment]
I am also a pensionada :) background: projectmanager, embedded and automation, electronics.
You are working on a very interesting project! 
Is there a way to exchange PM's? As I think this is not a platform to exchange personal information....

**Comment by freeck** [comment]
Robert,
Without having tested your configuration..I am 99% sure that you were debugging in RAM. So multiple breakpoints can be set. The excellent documentation of readthedocs confirms that no more than 2 hardware breakpoints are supported. So case closed as far as I am concerned...and wait until openocd supports flash-breakpoints. The debug-client for IDF and Sloeber are identical, so there is no reason to put more energy in it. And debugging in RAM is not an issue as long as you debug small functions.

**Comment by freeck** [comment]
I found out that setting multiple breakpoints using GDB Openocd debugging is not supported. Therefore I configured a "GDB hardware debugging" session. And now everthing works as expected.
Jantje, I will modify the documentation, but as the configuration is identical as IDF or any Eclipse-version, the effort will be minimal.

**Comment by freeck** [comment]
I found out that setting multiple SW-breakpoints using a "GDB Openocd debugging" is not working ( perhaps some configuration-property, I don't know). 
Therefore I configured a "GDB hardware debugging"-session. And now everything works as it  should.

@jantje Jantje, I will modify the documentation. As the configuration is identical to IDF or any other Eclipse-version, the effort will be minimal. Where possible I refer to the ReadTheDocs-documentation.

**Comment by RA5040** [comment]
Well that is excellent news!  

Please let me know when you have the documentation done because I've just tried it and it doesn't work for me (I get the same error: Warning:\nCannot insert breakpoint 1.\nCannot access memory at address 0x400d1094\n   Failed to execute MI command:).

Probably because I have some configuration set wrong (hopefully!).

**Comment by freeck** [comment]
Be aware that you still need IRAM_ATTR....for more than 2 breakpoints....

**Comment by freeck** [comment]
The reason "GDB Openocd debugging" didn't work was that **I used the wrong version of esp32.cfg** . 
So both "GDB Openocd debugging" and "GDB hardware debugging"-sessions work as they should.

**Comment by RA5040** [comment]
Actually you don't need the IRAM_ATTR. OpenOCD will support 2 hardware breakpoints, after that it does software breakpoints and you can use up to 32 software breakpoints in flash (and 32 in IRAM) ... not that I have tried that number.

But I have tried a bunch of them and after the 2nd you get a warning:
"Warn : xtensa_add_breakpoint: max HW slot reached, slot=2"

This works the same if you use GDB Hardware Debugging or GDB OpenOCD Debugging.  I don't know what the difference is between the two, to be honest ... except that with GDB OpenOCD Debugging Eclipse launches OpenOCD and with GDB Hardware Debugging I have to run OpenOCD from the command line.  Of course I may not be doing the GDB Hardware Debugging correctly (but I am following Espressif's instructions to the letter).

**Comment by freeck** [comment]
NO!! First try it before you state something.

**Comment by RA5040** [comment]
Could you tell me if I have to change any settings in C/C++ Build and C/C++ General to debug with Sloeber?  Currently my settings are:

![s43debug](https://user-images.githubusercontent.com/41873698/44916380-7b62b480-ad2d-11e8-8f94-cb9adbedd8e6.jpg)

**Comment by freeck** [comment]
these are the settings in 
![capture](https://user-images.githubusercontent.com/11876200/44916914-262ba080-ad37-11e8-8e65-a13e6f2c21df.JPG)
Sloeber, I do not see "Command to get compiler specs"

**Comment by jantje** [comment]
@RA5040 
These settings have nothing todo with debugging. They are for the indexer.
@freeck 
To see  "Command to get compiler specs" you have to select a language settings provider

**Comment by RA5040** [comment]
My question was:
"Could you tell me if I have to change any settings in C/C++ Build and C/C++ General to debug with Sloeber?"

@jantje 
As you know, I can debug in C/C++ but I CANNOT debug in Sloeber. So there is something different. If it is a setting then I would appreciate it if you would let me know what settings I should use. If it is not a setting then I would appreciate it if you would have a look yourself, try out OpenOCD, and find out what it is that is wrong.

**Comment by freeck** [comment]
Now I understand the mis-communication. I was totally fixed (and was the primary goal of this thread)  on making Sloeber fit for debugging ESP32 using openocd and jtag, but only for Arduino-style C/C++  programmes, and make a document. That was my contribution to the Sloeber-project. For me developing and debugging Arduino-programmes and C/C++ programmes are one and the same.... I understood your point after having read the instructions above  you refer to :). 
I wait for an answer from @Jantje on how to deal with this (should we start a new thread on this topic?).

**Comment by RA5040** [comment]
If we had been in the same room we could have saved ourselves a lot of work!  This way of working is a bit tricky ... still, a lot better than in the past when all the help available was in the technical documentation!.

Yes, I think it would be a good idea to start a new thread (will you do that?). What I will do also is to do a short video showing the debugging in C/C++. 

What seems to happen (and this is only a guess) is that when more than 2 breakpoints are defined, the 'software' breakpoint removes one of the breakpoints temporarily and inserts it in the new place. Then when the original is needed again it does the reverse. The reason I think that this may be the mechanism is that 2 breakpoints are fast; when you add one more it gets noticeably slower; 2 more slower still ... and so on.

But it does work well, even if it gets a bit slow.
