### ISSUE TITLE
Third Party index url's : cannot undo an error once the error is made

### ISSUE THREAD

**Issue by ghislainborremans** [Sloeber/arduino-eclipse-plugin#911]
I added a reference to a local Json file as "D:\Electronica\...."
When you push "Apply" the message  "Malformed url D:\Electronica\Libraries\hardware\package_jantje_index.json
unknown protocol: d"  appears.  Even when pressing "Restore Defaults" you keep getting the same message. 
I tried to edit the configuration file "io.sloeber.arduino.prefs" and discarded the reference but the error remains. It must be kept else where but i do not know where.

**Comment by ghislainborremans** [comment]
I reinstalled sloeber and that solved the problem.

**Comment by jantje** [comment]
The newest version includes package_jantje_index.json
File references should be given as file://D:\Electronica\Libraries\hardware\package_jantje_index.json
Clicking defaults should fix it. I'll try to reproduce.

**Comment by jantje** [comment]
It is very reproducible.
Needs to be fixed

**Comment by jantje** [comment]
Now available with the nightly and fixed

**Comment by lewiss66** [comment]
On version 4.2 It's still a problem.
I miss copy a link in the third party index url's:
(c:\user.....) instead of (https://raw.githubu....) and then I can't get rid of the error even though I supress the link. I click apply and I gives an error:
"Malformed url C:\Users\gilles\git\ds3231
unknown protocol: c"

**Comment by jantje** [comment]
>On version 4.2 It's still a problem.

indeed it is fixed in the nightly only for now.
